main: allFunOnStack.o reverse.o myAtof.o
	gcc allFunOnStack.o reverse.o myAtof.o -o main
allFunOnStack.o:allFunOnStack.c
	gcc -c allFunOnStack.c -o allFunOnStack.o
reverse.o:reverse.c
	gcc -c reverse.c -o reverse.o
myAtof.o:myAtof.c
	gcc -c myAtof.c -o myAtof.o