main.exe: allFunOnStack.o reverse.o
	gcc allFunOnStack.o reverse.o -o main.exe
allFunOnStack.o:allFunOnStack.c
	gcc -c allFunOnStack.c -o allFunOnStack.o
reverse.o:reverse.c
	gcc -c reverse.c -o reverse.o
